# Generated by Django 2.2 on 2019-05-20 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmode',
            name='pic_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.CreateModel(
            name='userp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
